<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent><groupId>io.github.felipemacedo1</groupId><artifactId>rizoma-parent</artifactId><version>0.3.0-SNAPSHOT</version></parent>
  <artifactId>rizoma-format-csv</artifactId><name>Rizoma CSV Format</name>
  <dependencies>
    <dependency><groupId>io.github.felipemacedo1</groupId><artifactId>rizoma-core</artifactId><version>${project.version}</version></dependency>
    <dependency><groupId>org.apache.commons</groupId><artifactId>commons-csv</artifactId><version>${commons.csv.version}</version></dependency>
    <dependency><groupId>commons-io</groupId><artifactId>commons-io</artifactId><version>${commons.io.version}</version></dependency>
    <dependency><groupId>org.junit.jupiter</groupId><artifactId>junit-jupiter</artifactId><scope>test</scope></dependency>
  </dependencies>
</project>
